POST http://127.0.0.1:8000/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "cristian@mail.com",
    "password": "cristian54321"
}

### Perfil
GET http://127.0.0.1:8000/api/v1/auth/profile
Accept: application/json
Authorization: Bearer 6|CqANB7WWqvNyOy2Tmn4v6vIk0AdYxVpm837WWanD267bdaf7


### Salir
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 6|CqANB7WWqvNyOy2Tmn4v6vIk0AdYxVpm837WWanD267bdaf7
